### ISSUE TITLE
repeat item

### ISSUE THREAD

**Issue by septs** [bitinn/animeshot#17]
see https://as.bitinn.net/search?q=%E4%BD%A0%E4%BB%A5%E4%B8%BA%E6%88%91%E6%98%AF%E8%B0%81

**Comment by septs** [comment]
https://as.bitinn.net/search?q=%E6%9C%89%E9%92%B1%E4%BA%BA%E5%B0%B1%E6%98%AF%E8%BF%99%E5%89%AF%E5%BE%B7

像这种超高近似度不打算在添加时处理下吗？

**Comment by bitinn** [comment]
Good to have, but not time for it.
